#!/bin/bash -l

#PBS -l walltime=30:00:00
#PBS -l nodes=6:ppn=6
#PBS -l mem=20gb
#PBS -l feature=intel
#PBS -m bea
#
# run using:
# 	--> module load worker/1.6.8-intel-2018a
#	--> wsub -batch reduced_fees_prototype_job_script_workers_nstepsarsa_8.pbs -data workers_data.csv -master

module purge

module load Python/3.6.4-intel-2018a
module load R/3.4.4-intel-2018a-X11-20180131
module load matplotlib/2.1.2-intel-2018a-Python-3.6.4

cd ~/C-Cure/MultiMAuS

echo submit directory: $PWD
echo jobid: $PBS_JOBID
echo hostname: $HOSTNAME
date
echo --- Start Job ---

python -u ./ccure_prototype/run_ccure_prototype.py --flat-fee 0.01 --relative-fee 0.003 --rl-agent NStepSarsa_8 --cs-models-r-filepath ~/C-Cure/CSModels.R --seed $seed --run-idx $run_idx --out-dir $WORKDIR/C-Cure/results --disable-ui

echo --- End Job ---
date